# Generated by Django 5.0 on 2023-12-29 07:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(default='Tirupur', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(default='Tirupur', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='dateofbirth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='student',
            name='emailid',
            field=models.EmailField(default='example@gmail.com', max_length=254, verbose_name=''),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Male', max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='mobile',
            field=models.CharField(default='9123456789', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pincode',
            field=models.CharField(default='641604', max_length=6, verbose_name='pincode'),
        ),
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(default='Tamil Nadu', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
