# Generated by Django 5.0 on 2023-12-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_remove_student_age_remove_student_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='known_languages',
            field=models.CharField(choices=[('1', 'Tamil'), ('2', 'English'), ('3', 'Hindi')], default='Tamil', max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(choices=[('1', 'Tirupur'), ('2', 'Coimbatore'), ('3', 'Chennai')], default='Tirupur', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.CharField(choices=[('1', 'TamilNadu'), ('2', 'Karnataka'), ('3', 'Kerala'), ('4', 'Andhra Pradesh')], default='Tamil Nadu', max_length=20),
        ),
    ]
