# Generated by Django 5.0 on 2023-12-29 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_student_known_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='known_languages',
        ),
    ]
